### ISSUE TITLE
Kali selenium

### ISSUE THREAD

**Issue by pokeswap** [breenmachine/httpscreenshot#1]
Running does not work on Kali:
 httpscreenshot/httpscreenshot.py", line 10, in <module>
    from selenium import webdriver
ImportError: No module named selenium

no apt-get install selenium or apt-get install python-selenium

**Comment by breenmachine** [comment]
Try pip - I run Kali and was able to use it to install successfully:

apt-get install python-pip
pip install selenium

**Comment by pokeswap** [comment]
Now, I am getting 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x2cccc50>> ignored
Exception AttributeError: "'Service' object has no[-] Oh no! Couldn't create the browser, Selenium blew up
 attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x2cccbd0>> ignored
[-] Oh no! Couldn't create the browser, Selenium blew up
!! Traceback (most recent call last):
!!   File "../httpscreenshot.py", line 161, in worker
    browser = setupBrowserProfile(headless)
!!   File "../httpscreenshot.py", line 141, in setupBrowserProfile
    time.sleep(1)
!! KeyboardInterrupt

over and over again

**Comment by breenmachine** [comment]
Interesting - I'll try to reproduce on Kali. It might be the case that Kali doesn't have a phantomjs package. Try to link the phantomjs binary in this repository to /usr/bin

sudo ln -s <path to phantomjs binary> /usr/bin/phantomjs

I'm not 100% sure that will work, going to try to spin up a VM soon and test. Thanks.
