### ISSUE TITLE
Close project - what's the use of the specific font ?

### ISSUE THREAD

**Issue by maaaaz** [breenmachine/httpscreenshot#18]
Hello @breenmachine,

Since I'm also developing a similar (yet older) project of `httpscreenshot`, named [`webscreenshot`](https://github.com/maaaaz/webscreenshot) (so much creativity though :p) also based on `phantomjs`, I'd like to know **why you are using specific font `LiberationSerif-BoldItalic.ttf`**: is it because of a particular bug (that I should be aware of) ?

Cheers.

**Comment by breenmachine** [comment]
Actually for no good reason other than the fact that I wanted the package
to be fully contained. Feel free to ignore.

I'm actually hoping to complete a rewrite of the tool that doesn't use
phantomjs, Im finding it unreliable and not worth the problems and
dependencies.

**Comment by maaaaz** [comment]
Okay !
I don't phantomjs to be that unreliable: of course there are some weird bugs but still it is useful. 

Do you already have any clue how to perform the same without a third-party tool ?

**Comment by breenmachine** [comment]
I find when we try to take screenshots of large ranges, I often run into
the case where I can successfully grab the HTML source of a page but
PhantomJS blows up for one reason or another.

I'd prefer to just render the HTML offline. Unfortunately we lose out on
Javascript parsing with this method, but for me it's worth the tradeoff.
