### ISSUE TITLE
Missing dependency geckodriver

### ISSUE THREAD

**Issue by eapolsniper** [breenmachine/httpscreenshot#24]
Installed httpscreenshot on 12/5/16 from repo onto Kali rolloing, fully updated, and received an error: Message: 'geckodriver' executable must be in PATH.

All listed dependencies were met. Manually downloaded geckodriver 11.1 from: https://github.com/mozilla/geckodriver/releases

Steps to fix:

mkdir /root/tools/gecko
cd /root/tools/gecko
wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz

gunzip geckodriver-v0.11.1-linux64.tar.gz
tar -xvf geckodriver-v0.11.1-linux64.tar.gz

ln -s /root/tools/gecko/geckodriver /usr/bin

**Comment by breenmachine** [comment]
Thanks, fixed. Have a few more fixes incoming as well related to this - unfortunately the newest version of FireFox/Geckodriver have issues accepting untrusted SSL certificates.
