### ISSUE TITLE
headless mode?

### ISSUE THREAD

**Issue by ITmustang** [breenmachine/httpscreenshot#27]
i am running httpscreenshot with the headless (-p) option enabled, but still getting the following warning..

_/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
will the httpscreenshot.py be updated to do this by default or is this user error? if user error, what needs to be changed?  thanks!

**Comment by breenmachine** [comment]
I plan on someday updating to support headless chrome instead of phantomjs, but haven't had the time. It's nothing you are doing wrong.
