### ISSUE TITLE
Kali and HttpScreenshot FYI.

### ISSUE THREAD

**Issue by jessekrembs** [breenmachine/httpscreenshot#4]
More of an FYI then a Issue. It appears that PhantomJS is not part of the Kali Linux repo system. I'm working to get this corrected as it seems like Kali and Httpscreenshot would be handy together.

**Comment by breenmachine** [comment]
That's actually why the phantomjs binary is in the repository. It's huge and ugly, and I probably should have just provided a link, but it's there for exactly that reason.

Thanks.

**Comment by jessekrembs** [comment]
ah...I am enlighted..
