### ISSUE TITLE
Target Operating Systems

### ISSUE THREAD

**Issue by RyPeck** [breenmachine/httpscreenshot#7]
@breenmachine this is just a question I wanted to get out of the way before I do some more work.

What are the Operating Systems/version httpscreenshot should aim to work with and be set up on?

I was thinking - 
Ubuntu 14.04
Kali
Mac OS X

**Comment by breenmachine** [comment]
Hey Ryan, that sounds great. Thanks a lot for the work on this! I had meant
to streamline the setup process but have been slammed for time lately.

**Comment by RyPeck** [comment]
@breenmachine so you agree with that target of machines to run on?

**Comment by breenmachine** [comment]
I think those would be great target OS's, yes.
